version: '3.8'

services:
  deviceDetails-service:
    image: device:latest
    ports:
      - "8080:8080"
    networks:
      - my_network

  automation-service:
    image: automation:latest
    ports:
      - "8081:8081"
    networks:
      - my_network

  notification-service:
    image: notification:latest
    ports:
      - "8082:8082"
    networks:
      - my_network



networks:
  my_network:
    driver: bridge